### ISSUE TITLE
Ability to request a specific date

### ISSUE THREAD

**Issue by RAlvarez66** [kjpou1/news_factory#1]
Hello!

This is a very nice project. May I suggest to add the ability to scrape a specific date or date range?
FF allows you to get info for a specify date: 
`/calendar?day=jun26.2024`

**Comment by kjpou1** [comment]
Thought about that but just did not need it for my purposes.

how would those be specified?  any ideas?

**Comment by RAlvarez66** [comment]
Hello,

Thank you for your reply.
I'm understanding your question as "what would be a good way to specify those parameters to my program?".
If I got it wrong, please let me know.

It could be something like:
`--start-date=1/1/2020 --end-date=1/1/2021`

The presence of those parameters would invalidate/ignore the parameter "-t", unless you want to code a "jump" and use "-t" as it (which is probably unnecessary). By "jump", I mean "scrape from date X to Z, skipping t period on every iteration". Once again, probably easier to just ignore "-t" and increase a single day on every iteration.
